# Generated by Django 4.0.1 on 2022-01-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
