# Generated by Django 4.0.1 on 2022-01-28 10:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_event_event_date_alter_event_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 28, 10, 44, 39, 926610, tzinfo=utc)),
        ),
    ]
