# Generated by Django 4.0.1 on 2022-01-30 15:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_event_event_date_alter_event_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 15, 35, 17, 863561, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 30, 15, 35, 17, 863578, tzinfo=utc)),
        ),
    ]
